# Generated by Django 5.2.1 on 2026-01-30 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AurexApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startupapplication',
            name='website',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
