# Generated by Django 5.2.1 on 2026-01-30 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AurexApp', '0003_investorapplication'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='timeline',
        ),
    ]
