# Generated by Django 5.2.1 on 2026-01-31 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(blank=True, max_length=20, null=True)),
                ("i_am_a", models.CharField(max_length=50)),
                ("message", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="InvestorApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=255)),
                ("category", models.CharField(max_length=100)),
                ("entity", models.CharField(blank=True, max_length=255)),
                ("designation", models.CharField(blank=True, max_length=255)),
                ("experience", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=20)),
                ("linkedin", models.CharField(blank=True, max_length=255)),
                ("city", models.CharField(blank=True, max_length=100)),
                ("stages", models.JSONField(default=list)),
                ("sectors", models.JSONField(default=list)),
                ("geography", models.CharField(max_length=50)),
                ("ticket", models.CharField(max_length=50)),
                ("style", models.CharField(max_length=50)),
                ("frequency", models.CharField(max_length=50)),
                ("deployment", models.CharField(max_length=50)),
                ("previous", models.CharField(max_length=10)),
                ("count", models.CharField(blank=True, max_length=50)),
                ("portfolio", models.TextField(blank=True)),
                ("engagement", models.JSONField(default=list)),
                ("involvement", models.CharField(max_length=50)),
                ("motivation", models.JSONField(default=list)),
                ("esg", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="StartupApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("startup_name", models.CharField(max_length=255)),
                ("incorporation_status", models.CharField(max_length=50)),
                ("entity_type", models.CharField(max_length=50)),
                ("incorporation_date", models.DateField(blank=True, null=True)),
                ("website", models.CharField(blank=True, max_length=255)),
                ("description", models.CharField(max_length=255)),
                ("address", models.TextField()),
                ("sector", models.CharField(max_length=100)),
                ("founders", models.CharField(max_length=255)),
                ("designations", models.CharField(max_length=255)),
                ("full_time", models.CharField(max_length=10)),
                ("linkedin", models.TextField(blank=True)),
                ("experience", models.TextField(blank=True)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=20)),
                ("stage", models.CharField(max_length=50)),
                ("bootstrapped", models.CharField(max_length=10)),
                (
                    "capital",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "revenue",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "burn",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                ("traction", models.TextField(blank=True)),
                ("raise_amount", models.DecimalField(decimal_places=2, max_digits=15)),
                ("funding_stage", models.CharField(max_length=50)),
                ("purpose", models.TextField()),
                (
                    "pitch_deck",
                    models.FileField(blank=True, null=True, upload_to="pitch_decks/"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
