# Generated by Django 5.2.1 on 2026-03-10 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AurexApp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EventRegistration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("email", models.EmailField(max_length=254)),
                ("contact_number", models.CharField(max_length=20)),
                ("organization_name", models.CharField(max_length=255)),
                ("city", models.CharField(max_length=150)),
                (
                    "registering_as",
                    models.CharField(
                        choices=[
                            ("founder", "Startup Founder"),
                            ("cofounder", "Co-founder"),
                            ("attendee", "General Attendee"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "startup_stage",
                    models.CharField(
                        choices=[
                            ("idea", "Idea Stage"),
                            ("mvp", "MVP Stage"),
                            ("early", "Early Revenue"),
                            ("growth", "Growth Stage"),
                        ],
                        max_length=50,
                    ),
                ),
                ("industry", models.CharField(max_length=255)),
                ("startup_brief", models.TextField()),
                ("bootstrapped", models.BooleanField()),
                (
                    "total_capital_invested",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "monthly_revenue",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "monthly_burn_rate",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "amount_to_raise",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "funding_stage",
                    models.CharField(
                        choices=[
                            ("pre_seed", "Pre-Seed"),
                            ("seed", "Seed"),
                            ("bridge", "Bridge"),
                            ("pre_series_a", "Pre-Series A"),
                            ("series_a", "Series A"),
                            ("series_b", "Series B+"),
                        ],
                        max_length=50,
                    ),
                ),
                ("interested_in_pitching", models.BooleanField()),
                ("pitch_deck_link", models.URLField(blank=True, null=True)),
                (
                    "pitch_deck_file",
                    models.FileField(blank=True, null=True, upload_to="pitch_decks/"),
                ),
                (
                    "pass_type",
                    models.CharField(
                        choices=[
                            ("event", "Event Registration Pass – ₹699"),
                            ("pitch", "Pitching Pass – ₹1499"),
                        ],
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
