# Generated by Django 5.2.1 on 2026-01-30 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AurexApp', '0002_alter_startupapplication_website'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestorApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=100)),
                ('entity', models.CharField(blank=True, max_length=255)),
                ('designation', models.CharField(blank=True, max_length=255)),
                ('experience', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('linkedin', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('stages', models.JSONField(default=list)),
                ('sectors', models.JSONField(default=list)),
                ('geography', models.CharField(max_length=50)),
                ('ticket', models.CharField(max_length=50)),
                ('style', models.CharField(max_length=50)),
                ('frequency', models.CharField(max_length=50)),
                ('deployment', models.CharField(max_length=50)),
                ('previous', models.CharField(max_length=10)),
                ('count', models.CharField(blank=True, max_length=50)),
                ('portfolio', models.TextField(blank=True)),
                ('engagement', models.JSONField(default=list)),
                ('involvement', models.CharField(max_length=50)),
                ('motivation', models.JSONField(default=list)),
                ('esg', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
