# Generated by Django 5.2.1 on 2026-04-16 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AurexApp", "0002_eventregistration"),
    ]

    operations = [
        migrations.CreateModel(
            name="WebinarRegistration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("company_name", models.CharField(max_length=150)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=15)),
                ("city", models.CharField(blank=True, max_length=100, null=True)),
                ("attended", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
