# Generated by Django 5.2.1 on 2026-05-13 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AurexApp", "0003_webinarregistration"),
    ]

    operations = [
        migrations.AddField(
            model_name="webinarregistration",
            name="payment_id",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
